# Generated by Django 4.0.4 on 2022-08-01 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Период')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Период',
                'verbose_name_plural': 'Периоды',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('time_project_created', models.DateTimeField(default='', verbose_name='Время создания проекта')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_finished', models.BooleanField(default=True, verbose_name='Завершение проекта')),
                ('link', models.URLField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='photos/%T/', verbose_name='Скриншот проекта')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myblog.places', verbose_name='Периоды')),
            ],
            options={
                'verbose_name': 'Мои проекты',
                'verbose_name_plural': 'Мои проекты',
                'ordering': ['time_project_created', 'is_finished', 'title'],
            },
        ),
    ]
