# Generated by Django 4.0.4 on 2022-08-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Дмитрий Ступак')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('date_time', models.DateField(auto_now_add=True, verbose_name='Дата рождения')),
                ('content', models.TextField(blank=True, verbose_name='Биография')),
                ('image', models.ImageField(upload_to='photos/%T/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Обо мне',
            },
        ),
        migrations.AlterField(
            model_name='projects',
            name='time_project_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания проекта'),
        ),
    ]
