# Generated by Django 4.0.4 on 2022-08-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_aboutinfo_alter_projects_time_project_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Для чего этот сайт')),
                ('link_projects', models.URLField(blank=True, max_length=255, verbose_name='Ссылка на проекты')),
                ('link_biography', models.URLField(blank=True, max_length=255, verbose_name='Ссылка на биографию')),
                ('link_reply', models.URLField(blank=True, max_length=255, verbose_name='Ссылка на ответ')),
            ],
            options={
                'verbose_name': 'О сайте',
            },
        ),
    ]
